# Generated by Django 5.2.5 on 2025-08-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attacksession',
            name='source_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attacksession',
            name='source_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attacksession',
            name='target_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attacksession',
            name='target_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attacksession',
            name='attack_type',
            field=models.CharField(choices=[('DDoS', 'DDoS'), ('Phishing', 'Phishing'), ('Malware', 'Malware'), ('Ransomware', 'Ransomware'), ('SQL Injection', 'SQL Injection'), ('Exploit', 'Exploit'), ('Worm', 'Worm')], max_length=100),
        ),
    ]
